// flow-typed signature: f519d3336e66e91c77bce2ee90ccb21f
// flow-typed version: <<STUB>>/cassandra-driver_v3.2.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cassandra-driver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cassandra-driver' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cassandra-driver/lib/auth/index' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/auth/plain-text-auth-provider' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/auth/provider' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/client-options' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/client' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/connection' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/control-connection' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/encoder' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/errors' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/execution-profile' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/host-connection-pool' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/host' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/aggregate' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/data-collection' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/event-debouncer' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/index' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/materialized-view' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/schema-function' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/schema-index' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/schema-parser' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/metadata/table-metadata' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/policies/address-resolution' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/policies/index' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/policies/load-balancing' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/policies/reconnection' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/policies/retry' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/policies/timestamp-generation' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/readers' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/request-handler' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/requests' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/stream-id-stack' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/streams' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/tokenizer' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/big-decimal' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/duration' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/index' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/inet-address' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/integer' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/local-date' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/local-time' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/protocol-version' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/result-set' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/result-stream' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/row' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/time-uuid' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/tuple' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/types/uuid' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/utils' {
  declare module.exports: any
}

declare module 'cassandra-driver/lib/writers' {
  declare module.exports: any
}

// Filename aliases
declare module 'cassandra-driver/index' {
  declare module.exports: $Exports<'cassandra-driver'>
}
declare module 'cassandra-driver/index.js' {
  declare module.exports: $Exports<'cassandra-driver'>
}
declare module 'cassandra-driver/lib/auth/index.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/auth/index'>
}
declare module 'cassandra-driver/lib/auth/plain-text-auth-provider.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/auth/plain-text-auth-provider'>
}
declare module 'cassandra-driver/lib/auth/provider.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/auth/provider'>
}
declare module 'cassandra-driver/lib/client-options.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/client-options'>
}
declare module 'cassandra-driver/lib/client.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/client'>
}
declare module 'cassandra-driver/lib/connection.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/connection'>
}
declare module 'cassandra-driver/lib/control-connection.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/control-connection'>
}
declare module 'cassandra-driver/lib/encoder.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/encoder'>
}
declare module 'cassandra-driver/lib/errors.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/errors'>
}
declare module 'cassandra-driver/lib/execution-profile.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/execution-profile'>
}
declare module 'cassandra-driver/lib/host-connection-pool.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/host-connection-pool'>
}
declare module 'cassandra-driver/lib/host.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/host'>
}
declare module 'cassandra-driver/lib/metadata/aggregate.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/aggregate'>
}
declare module 'cassandra-driver/lib/metadata/data-collection.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/data-collection'>
}
declare module 'cassandra-driver/lib/metadata/event-debouncer.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/event-debouncer'>
}
declare module 'cassandra-driver/lib/metadata/index.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/index'>
}
declare module 'cassandra-driver/lib/metadata/materialized-view.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/materialized-view'>
}
declare module 'cassandra-driver/lib/metadata/schema-function.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/schema-function'>
}
declare module 'cassandra-driver/lib/metadata/schema-index.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/schema-index'>
}
declare module 'cassandra-driver/lib/metadata/schema-parser.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/schema-parser'>
}
declare module 'cassandra-driver/lib/metadata/table-metadata.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/metadata/table-metadata'>
}
declare module 'cassandra-driver/lib/policies/address-resolution.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/policies/address-resolution'>
}
declare module 'cassandra-driver/lib/policies/index.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/policies/index'>
}
declare module 'cassandra-driver/lib/policies/load-balancing.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/policies/load-balancing'>
}
declare module 'cassandra-driver/lib/policies/reconnection.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/policies/reconnection'>
}
declare module 'cassandra-driver/lib/policies/retry.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/policies/retry'>
}
declare module 'cassandra-driver/lib/policies/timestamp-generation.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/policies/timestamp-generation'>
}
declare module 'cassandra-driver/lib/readers.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/readers'>
}
declare module 'cassandra-driver/lib/request-handler.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/request-handler'>
}
declare module 'cassandra-driver/lib/requests.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/requests'>
}
declare module 'cassandra-driver/lib/stream-id-stack.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/stream-id-stack'>
}
declare module 'cassandra-driver/lib/streams.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/streams'>
}
declare module 'cassandra-driver/lib/tokenizer.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/tokenizer'>
}
declare module 'cassandra-driver/lib/types/big-decimal.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/big-decimal'>
}
declare module 'cassandra-driver/lib/types/duration.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/duration'>
}
declare module 'cassandra-driver/lib/types/index.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/index'>
}
declare module 'cassandra-driver/lib/types/inet-address.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/inet-address'>
}
declare module 'cassandra-driver/lib/types/integer.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/integer'>
}
declare module 'cassandra-driver/lib/types/local-date.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/local-date'>
}
declare module 'cassandra-driver/lib/types/local-time.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/local-time'>
}
declare module 'cassandra-driver/lib/types/protocol-version.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/protocol-version'>
}
declare module 'cassandra-driver/lib/types/result-set.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/result-set'>
}
declare module 'cassandra-driver/lib/types/result-stream.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/result-stream'>
}
declare module 'cassandra-driver/lib/types/row.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/row'>
}
declare module 'cassandra-driver/lib/types/time-uuid.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/time-uuid'>
}
declare module 'cassandra-driver/lib/types/tuple.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/tuple'>
}
declare module 'cassandra-driver/lib/types/uuid.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/types/uuid'>
}
declare module 'cassandra-driver/lib/utils.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/utils'>
}
declare module 'cassandra-driver/lib/writers.js' {
  declare module.exports: $Exports<'cassandra-driver/lib/writers'>
}
