// flow-typed signature: e0ba04d0ec280bee2c3d24bff1e63d71
// flow-typed version: <<STUB>>/dataloader_v1.3.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dataloader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dataloader' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'dataloader/index' {
  declare module.exports: $Exports<'dataloader'>
}
declare module 'dataloader/index.js' {
  declare module.exports: $Exports<'dataloader'>
}
