// flow-typed signature: 985039dbe649a61befc5f65909793524
// flow-typed version: <<STUB>>/express-cassandra_v1.9.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-cassandra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-cassandra' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-cassandra/lib/expressCassandra' {
  declare module.exports: any
}

declare module 'express-cassandra/lib/orm/apollo_error' {
  declare module.exports: any
}

declare module 'express-cassandra/lib/orm/apollo_schemer' {
  declare module.exports: any
}

declare module 'express-cassandra/lib/orm/apollo' {
  declare module.exports: any
}

declare module 'express-cassandra/lib/orm/base_model' {
  declare module.exports: any
}

declare module 'express-cassandra/lib/orm/cassandra_types' {
  declare module.exports: any
}

// Filename aliases
declare module 'express-cassandra/lib/expressCassandra.js' {
  declare module.exports: $Exports<'express-cassandra/lib/expressCassandra'>
}
declare module 'express-cassandra/lib/orm/apollo_error.js' {
  declare module.exports: $Exports<'express-cassandra/lib/orm/apollo_error'>
}
declare module 'express-cassandra/lib/orm/apollo_schemer.js' {
  declare module.exports: $Exports<'express-cassandra/lib/orm/apollo_schemer'>
}
declare module 'express-cassandra/lib/orm/apollo.js' {
  declare module.exports: $Exports<'express-cassandra/lib/orm/apollo'>
}
declare module 'express-cassandra/lib/orm/base_model.js' {
  declare module.exports: $Exports<'express-cassandra/lib/orm/base_model'>
}
declare module 'express-cassandra/lib/orm/cassandra_types.js' {
  declare module.exports: $Exports<'express-cassandra/lib/orm/cassandra_types'>
}
