// flow-typed signature: 948cd971ca2d8489e3a459643047ff8e
// flow-typed version: <<STUB>>/found-relay_v0.3.0-alpha.5/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'found-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'found-relay' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'found-relay/lib/classic/index' {
  declare module.exports: any
}

declare module 'found-relay/lib/classic/RelayRouteRenderer' {
  declare module.exports: any
}

declare module 'found-relay/lib/classic/Resolver' {
  declare module.exports: any
}

declare module 'found-relay/lib/index' {
  declare module.exports: any
}

declare module 'found-relay/lib/modern/index' {
  declare module.exports: any
}

declare module 'found-relay/lib/modern/QuerySubscription' {
  declare module.exports: any
}

declare module 'found-relay/lib/modern/ReadyStateRenderer' {
  declare module.exports: any
}

declare module 'found-relay/lib/modern/Resolver' {
  declare module.exports: any
}

// Filename aliases
declare module 'found-relay/lib/classic/index.js' {
  declare module.exports: $Exports<'found-relay/lib/classic/index'>
}
declare module 'found-relay/lib/classic/RelayRouteRenderer.js' {
  declare module.exports: $Exports<'found-relay/lib/classic/RelayRouteRenderer'>
}
declare module 'found-relay/lib/classic/Resolver.js' {
  declare module.exports: $Exports<'found-relay/lib/classic/Resolver'>
}
declare module 'found-relay/lib/index.js' {
  declare module.exports: $Exports<'found-relay/lib/index'>
}
declare module 'found-relay/lib/modern/index.js' {
  declare module.exports: $Exports<'found-relay/lib/modern/index'>
}
declare module 'found-relay/lib/modern/QuerySubscription.js' {
  declare module.exports: $Exports<'found-relay/lib/modern/QuerySubscription'>
}
declare module 'found-relay/lib/modern/ReadyStateRenderer.js' {
  declare module.exports: $Exports<'found-relay/lib/modern/ReadyStateRenderer'>
}
declare module 'found-relay/lib/modern/Resolver.js' {
  declare module.exports: $Exports<'found-relay/lib/modern/Resolver'>
}
