// flow-typed signature: 7ee719481aed3bcca64765a101376038
// flow-typed version: <<STUB>>/graphql-iso-date_v3.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-iso-date'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-iso-date' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-iso-date/dist/date/index' {
  declare module.exports: any
}

declare module 'graphql-iso-date/dist/dateTime/index' {
  declare module.exports: any
}

declare module 'graphql-iso-date/dist/index' {
  declare module.exports: any
}

declare module 'graphql-iso-date/dist/time/index' {
  declare module.exports: any
}

declare module 'graphql-iso-date/dist/utils/formatter' {
  declare module.exports: any
}

declare module 'graphql-iso-date/dist/utils/index' {
  declare module.exports: any
}

declare module 'graphql-iso-date/dist/utils/validator' {
  declare module.exports: any
}

// Filename aliases
declare module 'graphql-iso-date/dist/date/index.js' {
  declare module.exports: $Exports<'graphql-iso-date/dist/date/index'>
}
declare module 'graphql-iso-date/dist/dateTime/index.js' {
  declare module.exports: $Exports<'graphql-iso-date/dist/dateTime/index'>
}
declare module 'graphql-iso-date/dist/index.js' {
  declare module.exports: $Exports<'graphql-iso-date/dist/index'>
}
declare module 'graphql-iso-date/dist/time/index.js' {
  declare module.exports: $Exports<'graphql-iso-date/dist/time/index'>
}
declare module 'graphql-iso-date/dist/utils/formatter.js' {
  declare module.exports: $Exports<'graphql-iso-date/dist/utils/formatter'>
}
declare module 'graphql-iso-date/dist/utils/index.js' {
  declare module.exports: $Exports<'graphql-iso-date/dist/utils/index'>
}
declare module 'graphql-iso-date/dist/utils/validator.js' {
  declare module.exports: $Exports<'graphql-iso-date/dist/utils/validator'>
}
