// flow-typed signature: 34ff6335f09d4a4a54e7da39d9c656c0
// flow-typed version: <<STUB>>/react-code-splitting_v1.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-code-splitting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-code-splitting' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-code-splitting/dist/react-code-splitting.min' {
  declare module.exports: any
}

declare module 'react-code-splitting/example/App/Fat' {
  declare module.exports: any
}

declare module 'react-code-splitting/example/App/index' {
  declare module.exports: any
}

declare module 'react-code-splitting/example/webpack.config' {
  declare module.exports: any
}

declare module 'react-code-splitting/src/index' {
  declare module.exports: any
}

declare module 'react-code-splitting/webpack.config' {
  declare module.exports: any
}

// Filename aliases
declare module 'react-code-splitting/dist/react-code-splitting.min.js' {
  declare module.exports: $Exports<'react-code-splitting/dist/react-code-splitting.min'>
}
declare module 'react-code-splitting/example/App/Fat.js' {
  declare module.exports: $Exports<'react-code-splitting/example/App/Fat'>
}
declare module 'react-code-splitting/example/App/index.js' {
  declare module.exports: $Exports<'react-code-splitting/example/App/index'>
}
declare module 'react-code-splitting/example/webpack.config.js' {
  declare module.exports: $Exports<'react-code-splitting/example/webpack.config'>
}
declare module 'react-code-splitting/src/index.js' {
  declare module.exports: $Exports<'react-code-splitting/src/index'>
}
declare module 'react-code-splitting/webpack.config.js' {
  declare module.exports: $Exports<'react-code-splitting/webpack.config'>
}
