// flow-typed signature: 9e8a9bf3bf3c7be5b273d4296a241a5c
// flow-typed version: <<STUB>>/sort-json_v1.4.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sort-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sort-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sort-json/cmd' {
  declare module.exports: any;
}

declare module 'sort-json/tests/visit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sort-json/cmd.js' {
  declare module.exports: $Exports<'sort-json/cmd'>;
}
declare module 'sort-json/index' {
  declare module.exports: $Exports<'sort-json'>;
}
declare module 'sort-json/index.js' {
  declare module.exports: $Exports<'sort-json'>;
}
declare module 'sort-json/tests/visit.js' {
  declare module.exports: $Exports<'sort-json/tests/visit'>;
}
